# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    #projects: '**/*.csproj'
    projects: 'Package/Core/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  # my working directory is src
  

# Package a project
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Package/Core/Core.Lib/*.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@0
  displayName: 'NuGet authenticate'

# Push a project
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    publishVstsFeed: 'NugetArtifactMVVMUniversal/PublicPackagesV2'
    nugetConfigPath: '$(Build.WorkingDirectory)/NuGet.config'
    allowPackageConflicts: true
